#!/usr/bin/env python3
"""Run vLLM trace-replay with requests loaded from JSONL.

This script uses the same JSONL schema as collect_intermediate_states.py:
{"request_id": "...", "prompt": "..."}
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

import torch


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="gpt2", help="HF model id/path for vLLM init.")
    p.add_argument("--input-jsonl", required=True, help="Input requests JSONL.")
    p.add_argument(
        "--trace-db-path",
        default=os.environ.get("TRACE_REPLAY_DB_PATH", ""),
        help="Path to trace_db.pt. If missing and --auto-create-trace-db is set, "
        "a synthetic db is generated from request_ids.",
    )
    p.add_argument(
        "--auto-create-trace-db",
        action="store_true",
        help="Create a synthetic trace db when --trace-db-path is absent.",
    )
    p.add_argument("--max-tokens", type=int, default=50)
    p.add_argument("--max-model-len", type=int, default=256)
    p.add_argument("--temperature", type=float, default=0.0)
    p.add_argument(
        "--report-path",
        default="",
        help="Optional schedule report path. Defaults to a temp file.",
    )
    return p.parse_args()


def load_requests(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if "request_id" not in row or "prompt" not in row:
                raise ValueError(f"line {line_no}: request_id/prompt missing")
            rows.append({"request_id": str(row["request_id"]), "prompt": str(row["prompt"])})
    if not rows:
        raise ValueError("No requests found in input JSONL.")
    return rows


def write_synthetic_trace_db(path: Path, request_ids: list[str]) -> None:
    records: dict[str, dict[str, Any]] = {}
    base = 1000
    for idx, req_id in enumerate(request_ids):
        seq = list(range(base + idx * 50, base + idx * 50 + 128))
        records[req_id] = {"step_token_ids": seq}
    payload = {
        "meta": {
            "demo": True,
            "description": "Synthetic trace db generated by run_vllm.py",
            "num_requests": len(records),
        },
        "records": records,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(payload, path)


def main() -> int:
    args = parse_args()
    requests = load_requests(Path(args.input_jsonl))

    trace_db_path = Path(args.trace_db_path) if args.trace_db_path else None
    if trace_db_path is None or not trace_db_path.is_file():
        if not args.auto_create_trace_db:
            raise FileNotFoundError(
                "TRACE_REPLAY_DB_PATH/--trace-db-path is missing. "
                "Pass --auto-create-trace-db to generate one."
            )
        tmp = Path(tempfile.mkdtemp(prefix="vllm-trace-replay-"))
        trace_db_path = tmp / "trace_db.pt"
        write_synthetic_trace_db(trace_db_path, [r["request_id"] for r in requests])
        print(f"[run_vllm] generated synthetic trace db: {trace_db_path}", file=sys.stderr)

    report_path = Path(args.report_path) if args.report_path else (
        Path(tempfile.mkdtemp(prefix="vllm-trace-replay-report-"))
        / "schedule_report.jsonl"
    )

    # Must be set before importing vLLM.
    os.environ["VLLM_PLUGINS"] = "trace_replay"
    os.environ["TRACE_REPLAY_DB_PATH"] = str(trace_db_path)
    os.environ["TRACE_REPLAY_REPORT_PATH"] = str(report_path)

    # Support both installed-package layout (`from vllm import LLM`) and
    # source-tree namespace layout (`vllm` namespace package without __init__).
    try:
        from vllm import LLM, SamplingParams
    except Exception:
        from vllm.entrypoints.llm import LLM
        from vllm.sampling_params import SamplingParams
    from vllm.outputs import RequestOutput
    from vllm.platforms import current_platform

    platform_cls = current_platform.__class__
    if platform_cls.__module__ != "trace_replay_plugin.my_dummy_platform":
        raise RuntimeError(
            "trace_replay platform is not active. "
            f"Resolved platform={platform_cls.__module__}.{platform_cls.__name__}. "
            "Check plugin installation and Python version compatibility."
        )

    llm = LLM(
        model=args.model,
        load_format="dummy",
        enforce_eager=True,
        max_model_len=args.max_model_len,
        tensor_parallel_size=1,
    )
    sampling_params = SamplingParams(
        max_tokens=args.max_tokens,
        temperature=args.temperature,
    )

    # Add requests with explicit request_id so they align with trace keys.
    for row in requests:
        llm.llm_engine.add_request(
            request_id=row["request_id"],
            prompt=row["prompt"],
            params=sampling_params,
        )

    finished_outputs: list[RequestOutput] = []
    while llm.llm_engine.has_unfinished_requests():
        step_outputs = llm.llm_engine.step()
        for out in step_outputs:
            if isinstance(out, RequestOutput) and out.finished:
                finished_outputs.append(out)

    # Keep original JSONL order.
    order = {row["request_id"]: i for i, row in enumerate(requests)}
    finished_outputs.sort(key=lambda x: order.get(x.request_id, 10**9))

    print("[run_vllm] finished outputs:")
    for out in finished_outputs:
        first = out.outputs[0] if out.outputs else None
        token_ids = list(first.token_ids) if first else []
        preview = (first.text if first else "")[:120]
        print(
            f"  request_id={out.request_id!r} "
            f"n_tokens={len(token_ids)} preview={preview!r}"
        )

    print(f"[run_vllm] trace_db={trace_db_path}")
    print(f"[run_vllm] schedule_report={report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
